educacioncuaz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('educuaz/', include('usuarios.urls')),
]

usuarios/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from . import templates

app_name='eduacionapp'

#Aqui se determinan las urls a las que se puede acceder a la página
urlpatterns = [
    path('home/', views.Home, name='home'),
    path('login/', views.Login.as_view(), name='login'),
    path('register/', views.Register.as_view(), name='register'),
    path('editar/<int:id>', views.editar_usuario, name='editar'),
    path('editar_permisos/<int:id>', views.editar_permisos, name='editar_permisos'),
    path('delete/<int:id>/', views.elimina_usuario, name='borrar'),
    path(r'logout/', auth_views.LogoutView.as_view(), name='logout'),


]

usuarios/models.py
from django.contrib.auth.models import User
from django.db import models

usuarios/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


class UsuarioForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].label = 'Introduce tu contraseña'
        self.fields['password2'].label = 'Introduce tu contraseña nuevamente'
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''
        self.fields['username'].help_text = ''

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido'}),
            'username': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Matrícula'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}),
        }

usuarios/views.py
from .forms import UsuarioForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

from .decorators import unauthenticated_user
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.shortcuts import render, redirect
#importa los grupos que tienen diferentes permisos
from django.contrib.auth.models import Group


#Esta clase se utiliza para realizar el registro de un nuevo usuario en la plataforma web
@method_decorator(unauthenticated_user, name='dispatch')
class Register(CreateView):
    model = User
    template_name = "register.html"
    form_class = UsuarioForm

    success_url = reverse_lazy('eduacionapp:login')

#Esta clase se utiliza para iniciar sesion dentro de la plataforma web
@method_decorator(unauthenticated_user, name='dispatch')
class Login(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('eduacionapp:admin')

#Esta clase es para organizar el contenido base de la plataforma web

def Home(request):
    usuarios = User.objects.all()
    context = {'usuarios': usuarios}
    return render(request, 'home.html', context)



class ListaUsuario(ListView):
    model = User

def editar_usuario(request, id):
    usuario = User.objects.get(id=id)
    form = UsuarioForm(instance=usuario)
    if request.method == 'POST':
        form = UsuarioForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            return redirect('eduacionapp:home')
    context = {'form': form}
    return render(request, 'editar_usuario.html', context)

# Elimina un usario
def elimina_usuario(request, id):
    usua = User.objects.get(id=id)
    if request.method == "POST":
        usua.delete()
        return redirect('/')
    context = {'usua': usua}
    return render(request, 'delete.html', context)

#Modifica los permisos de un usuario
def editar_permisos(request, id):
    usua =User.objects.get(id=id)
    group_al = Group.objects.get(name='alumno')
    group_pro = Group.objects.get(name='profesor')


    # seleccionar el tipo de permiso a mano
    if request.method == "POST":
        #identidica el permiso
        #Eres un estudiante
        if '_estudiante' in request.POST:
            print(usua.groups.all()[0])
            #quitamos los grupos
            usua.groups.clear()
            #le da permiso de estudiante
            usua.groups.add(group_al)


        #Entonces eres un profesor
        else:
            # Le da permiso de profesor
            usua.groups.clear()
            usua.groups.add(group_pro)
        #usua.delete()
        return redirect('eduacionapp:home')
    #Se le entrega los datos para mostrarlos
    context = {'usua': usua}
    return render(request, 'editar_permisos.html', context)

usuarios/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
            crossorigin="anonymous">
        <link rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
            crossorigin="anonymous">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

<link rel="stylesheet"
            href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
             crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
            crossorigin="anonymous"></script>
 <script
          src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
          crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

{% block head %} {% endblock %}
    </head>
    <body>
        <div>
            {% block navbar %} {% endblock %}
            <br>
            <br>
            <br>
            {% block content %}{% endblock %}
        </div>

    </body>

</html>

usuarios/templates/base_us.html
{% extends "base_bootstrap.html" %}
{% block navbar %}

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    {% if user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'eduacionapp:home' %}">Educación Contínua</a>
    {% else %}
     <a class="navbar-brand" href="#">Educación Contínua</a>
    {% endif %}  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#barranavegacion" aria-expanded="false" aria-controls="barranavegacion" aria-label="Toggle navigation">
      </button>
      <div class="collapse navbar-collapse" id="barranavegacion">
        <ul class="navbar-nav">

        </ul>
      </div>

    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'eduacionapp:logout' %}?next={% url 'eduacionapp:login' %}">{{ user.get_username }} - Cerrar sesión</a>
        </li>
        {% else %}
        <li>
            <a href="{% url 'eduacionapp:login' %}?next={{request.path}}">Iniciar sesión</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>

{% endblock %}

usuarios/templates/editar_usuario.html
{% extends "base_us.html" %}
{% block title %}
    Editar Usuario
{% endblock %}

{% block content %}

    <div class="container card mb-3" style="width: 30rem;">
    <div class="sign-form ">
        <br>
     <form method="post">
      {% csrf_token %}
      <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Matrícula:</span>
                </div>
                {{ form.username }}
            </div>
         <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Nombre(s):</span>
                </div>
                {{ form.first_name }}
            </div>
         <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Apellido(s):</span>
                </div>
                {{ form.last_name }}
            </div>
         <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Correo:</span>
                </div>
                {{ form.email }}
            </div>
         <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Nueva contraseña:</span>
                </div>
                {{ form.password1 }}
            </div>
         <p class="d-flex card-text mt-3 login_container"> ° La contraseña debe de tener de mínimo 8 caracteres</p>
         <p class="d-flex card-text mt-3 login_container"> ° La contraseña debe no debe de ser completamente numérica</p>
         <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Confirma contraseña:</span>
                </div>
                {{ form.password2 }}
            </div>
     <div class="d-flex justify-content-center mt-4 login_container">
      <button class="btn  btn-success" type="submit">Agregar</button>
      <button class="btn  btn-danger" type="button"><a href="{% url 'eduacionapp:home' %}"> Cancelar  </a>   </button>

     </div>

      <a class="d-flex card-text justify-content-center mt-3 login_container"  href="{% url 'eduacionapp:login' %}">Accede con una cuenta</a>
     </form>
    </div>
    </div>
{% endblock %}

usuarios/templates/home.html
{% extends "base_us.html" %}
{% block title %}
Login
{% endblock %}

{% load static %}

{% block content %}
    <!-- Cosas que muestra para el administrador  -->
    {% if request.user.is_staff %}
    <h2 class="app-page-title">  Lista de usuarios</h2>
    <div class="app-card app-card-orders-table shadow-sm mb-5">
    <table class="table">
        <thead>
            <th>Matricula</th>
            <th>Nombre</th>
            <th>Acciones</th>
        </thead>
        <tbody>
            {% for user in usuarios %}
            <tr>
                {% if user.username != "admin" %}
                <td>{{user.username}}</td>
                <td>{{user.first_name}} {{user.last_name}}</td>
                <td>
                    <a href="{% url 'eduacionapp:editar' user.id %}" class="btn btn-primary btn-sm">Modificar Informacion</a>
                    <a href="{% url 'eduacionapp:editar_permisos' user.id %}" class="btn btn-primary btn-sm">Modificar Permisos</a>
                    <a href="{% url 'eduacionapp:borrar' user.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                </td>
            </tr>

                {% endif %}

            {% endfor %}
        </tbody>
    </table>
</div>
    {% else %}
    {% if user.is_authenticated %}
<div class="card-deck card mb-3">
<!-- Cosas que muestra para el alumno  -->
  {% if request.user.groups.all.0.name == "alumno" %}
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Alumno</h5>
      <p class="card-text">Bienvenido alumno a esta sesión.</p>
      <a class="d-flex card-text justify-content-center mt-3 login_container" href="#">:)</a>
    </div>
  </div>
  <!-- Cosas que muestra para el profesor  -->
{% elif request.user.groups.all.0.name == "profesor"%}
    <div class="card">
    <div class="card-body">
      <h5 class="card-title">Docente</h5>
      <p class="card-text">Bienvenido docente a esta sesión.</p>
      <a class="d-flex card-text justify-content-center mt-3 login_container" href="#">:)</a>
    </div>
  </div>
{% endif %}
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Moodle</h5>
      <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
       <a class="d-flex card-text justify-content-center mt-3 login_container" href="#">Acceder</a>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Chamilo</h5>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
      <a class="d-flex card-text justify-content-center mt-3 login_container" href="#">Acceder</a>
    </div>
  </div>

</div>
    {% endif %}
    {% endif %}

{% endblock %}

usuarios/templates/login.html
{% extends "base_us.html" %}
{% block title %}
    Login
{% endblock %}
{% load static %}
<style>
    .card {
        margin: 0 auto; /* Added */
        float: none; /* Added */
        margin-bottom: 10px; /* Added */
    }
</style>
{% block content %}
    <div class="container card mb-3" style="width: 18rem;">
        <br>
        <img src="{% static 'images/uaz.jpg' %} " class="card-img   d-flex justify-content-center" alt="Card image cap">
        <br>
        <form method="post">
            {% csrf_token %}
            <div class="input-group mb-3 justify-content-center">
                <div class="input-group-append">
                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                {{ form.username }}
            </div>
            <div class="input-group mb-3 justify-content-center">
                <div class="input-group-append">
                    <span class="input-group-text"><i class="fas fa-key"></i></span>
                </div>
                {{ form.password }}
            </div>
            {% if user.is_anonymous %}
                <div class="d-flex justify-content-center mt-3 login_container">
                    <input class="btn login_btn" type="submit" value="Acceder" href="{% url 'eduacionapp:home' %}">
                </div>
            {% endif %}
            <a class="d-flex card-text justify-content-center mt-3 login_container" href="#">¿Olvidaste tu contraseña?</a>
            <a class="d-flex card-text justify-content-center mt-3 login_container"  href="{% url 'eduacionapp:register' %}">Registrate</a>

        </form>
        <br>
    </div>


{% endblock %}

usuarios/templates/register.html
{% extends "base_us.html" %}
{% block title %}
    Registrar Nuevo Usuario
{% endblock %}

{% block content %}

    <div class="container card mb-3" style="width: 30rem;">
    <div class="sign-form ">
        <br>
     <form method="post">
      {% csrf_token %}
      <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Matrícula:</span>
                </div>
                {{ form.username }}
            </div>
         <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Nombre(s):</span>
                </div>
                {{ form.first_name }}
            </div>
         <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Apellido(s):</span>
                </div>
                {{ form.last_name }}
            </div>
         <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Correo:</span>
                </div>
                {{ form.email }}
            </div>
         <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Nueva contraseña:</span>
                </div>
                {{ form.password1 }}
            </div>
         <p class="d-flex card-text mt-3 login_container"> ° La contraseña debe de tener de mínimo 8 caracteres</p>
         <p class="d-flex card-text mt-3 login_container"> ° La contraseña debe no debe de ser completamente numérica</p>
         <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text">Confirma contraseña:</span>
                </div>
                {{ form.password2 }}
            </div>
     <div class="d-flex justify-content-center mt-3 login_container">
      <button class="btn  btn-success" type="submit">Agregar</button>
         <button class="btn  btn-danger" type="button"><a href="{% url 'eduacionapp:home' %}"> Cancelar  </a>   </button>
     </div>
      <a class="d-flex card-text justify-content-center mt-3 login_container"  href="{% url 'eduacionapp:login' %}">Accede con una cuenta</a>
     </form>
    </div>
    </div>
{% endblock %}